/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOPOSDEFCORRGAUSS
#define ROOPOSDEFCORRGAUSS

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooPosDefCorrGauss : public RooAbsReal {
public:
  RooPosDefCorrGauss() {} ; 
  RooPosDefCorrGauss(const char *name, const char *title,
	      RooAbsReal& _mean,
	      RooAbsReal& _sigma,
	      RooAbsReal& _base_par, Bool_t _changeSign = kFALSE);
  RooPosDefCorrGauss(const RooPosDefCorrGauss& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooPosDefCorrGauss(*this,newname); }
  inline virtual ~RooPosDefCorrGauss() { }

protected:

  RooRealProxy mean ;
  RooRealProxy sigma ;
  RooRealProxy base_par ;
  Bool_t changeSign ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooPosDefCorrGauss,1) // Your description goes here...
};
 
#endif
